In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Funnel_Analysis_Data.csv")

In [5]:
df

,User ID,Session ID,Event Time,Event,Device,Region,Channel,Product Category,Revenue,Bonus Flag
0,USR-00001,SES-00001,2026-01-07 23:46:20.358501,Browse,Tablet,South,Organic,Electronics,0.0,Yes
1,USR-00001,SES-00001,2026-01-07 23:49:20.358501,Add to Cart,Tablet,South,Organic,Electronics,0.0,Yes
2,USR-00001,SES-00001,2026-01-07 23:51:20.358501,Checkout,Tablet,South,Organic,Electronics,0.0,Yes
3,USR-00002,SES-00002,2026-01-04 21:06:42.296010,Browse,Desktop,East,Email,Sports,0.0,Yes
4,USR-00002,SES-00002,2026-01-04 21:10:42.296010,Add to Cart,Desktop,East,Email,Sports,0.0,Yes
...,...,...,...,...,...,...,...,...,...,...
21404,USR-09997,SES-09997,2026-01-03 14:01:06.074656,Checkout,Mobile,North,Google Ads,Sports,0.0,Yes
21405,USR-09998,SES-09998,2025-12-17 06:17:57.577958,Browse,Desktop,North,Social Media,Beauty,0.0,Yes
21406,USR-09998,SES-09998,2025-12-17 06:22:57.577958,Add to Cart,Desktop,North,Social Media,Beauty,0.0,Yes
21407,USR-09999,SES-09999,2025-12-30 15:47:23.983289,Browse,Mobile,East,Email,Sports,0.0,Yes
21408,USR-10000,SES-10000,2025-12-19 18:57:10.591617,Browse,Tablet,East,Email,Beauty,0.0,Yes

In [6]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [7]:
df

,user_id,session_id,event_time,event,device,region,channel,product_category,revenue,bonus_flag
0,USR-00001,SES-00001,2026-01-07 23:46:20.358501,Browse,Tablet,South,Organic,Electronics,0.0,Yes
1,USR-00001,SES-00001,2026-01-07 23:49:20.358501,Add to Cart,Tablet,South,Organic,Electronics,0.0,Yes
2,USR-00001,SES-00001,2026-01-07 23:51:20.358501,Checkout,Tablet,South,Organic,Electronics,0.0,Yes
3,USR-00002,SES-00002,2026-01-04 21:06:42.296010,Browse,Desktop,East,Email,Sports,0.0,Yes
4,USR-00002,SES-00002,2026-01-04 21:10:42.296010,Add to Cart,Desktop,East,Email,Sports,0.0,Yes
...,...,...,...,...,...,...,...,...,...,...
21404,USR-09997,SES-09997,2026-01-03 14:01:06.074656,Checkout,Mobile,North,Google Ads,Sports,0.0,Yes
21405,USR-09998,SES-09998,2025-12-17 06:17:57.577958,Browse,Desktop,North,Social Media,Beauty,0.0,Yes
21406,USR-09998,SES-09998,2025-12-17 06:22:57.577958,Add to Cart,Desktop,North,Social Media,Beauty,0.0,Yes
21407,USR-09999,SES-09999,2025-12-30 15:47:23.983289,Browse,Mobile,East,Email,Sports,0.0,Yes
21408,USR-10000,SES-10000,2025-12-19 18:57:10.591617,Browse,Tablet,East,Email,Beauty,0.0,Yes

In [8]:
df.isnull().sum()

user_id             0
session_id          0
event_time          0
event               0
device              0
region              0
channel             0
product_category    0
revenue             0
bonus_flag          0
dtype: int64

In [9]:
pip install pandas sqlalchemy psycopg2

Requirement already satisfied: pandas in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: sqlalchemy in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (2.0.48)
Collecting psycopg2
  Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: greenlet>=1 in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\teju\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   -------------- ------------------------- 1.0/2.8 MB 3.2 MB/s eta 0:00:01
   ---------------------- ----------------- 1.6/2.8 MB 3.5 MB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 3.6 MB/s  0:00:01
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.11
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
from sqlalchemy import create_engine

# Connecting to PostgreSQL
username = "postgres"
password = "767691"
host = "localhost"
port = "5432"
database = "funnel_data"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Table name
table_name = "funnel"

# Load DataFrame into PostgreSQL
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'funnel' in database 'funnel_data'.